const {app,BrowserWindow,WebContentsView,session,ipcMain,shell}=require('electron');const path=require('path');const crypto=require('crypto');const nodemailer=require('nodemailer');
let win=null,browserView=null,tabs=new Map(),activeId=null,bounds={x:320,y:120,width:900,height:650};
const isDev=!!process.env.VITE_DEV_SERVER_URL;const http=/^https?:\\/\\/i;
function emit(){win?.webContents.send('browser:state',{activeId,tabs:[...tabs.values()].map(x=>x.meta)})}
function apply(){const t=tabs.get(activeId);if(t){t.view.setBounds(bounds);t.view.setVisible(true)}for(const [id,x] of tabs)if(id!==activeId)x.view.setVisible(false)}
async function createTab(url='https://www.google.com'){const id=crypto.randomUUID();const view=new WebContentsView({webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,session:session.fromPartition('persist:xythol-browser')}});win.contentView.addChildView(view);view.setBounds(bounds);const meta={id,title:'New tab',url,loading:true,pinned:false};tabs.set(id,{meta,view});view.webContents.setWindowOpenHandler(({url})=>{if(http.test(url))view.webContents.loadURL(url);return {action:'deny'}});view.webContents.on('will-navigate',(e,url)=>{if(!http.test(url))e.preventDefault()});view.webContents.on('did-start-loading',()=>{meta.loading=true;emit()});view.webContents.on('did-stop-loading',()=>{meta.loading=false;meta.title=view.webContents.getTitle()||meta.title;meta.url=view.webContents.getURL()||meta.url;emit()});view.webContents.on('page-title-updated',(e,title)=>{e.preventDefault();meta.title=title;emit()});view.webContents.on('did-navigate',(_,url)=>{meta.url=url;emit()});await view.webContents.loadURL(url);activeId=id;apply();emit();return{id}}
function current(){return activeId?tabs.get(activeId):null}
function setup(){win=new BrowserWindow({width:1440,height:900,minWidth:1080,minHeight:680,show:false,backgroundColor:'#fbfaf8',title:'Xythol Mail',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.once('ready-to-show',()=>win.show());win.on('closed',()=>{for(const x of tabs.values())x.view.webContents.close();tabs.clear();win=null});const ses=session.fromPartition('persist:xythol-browser');ses.setPermissionRequestHandler((_wc,_p,cb)=>cb(false));if(isDev)win.loadURL(process.env.VITE_DEV_SERVER_URL);else win.loadFile(path.join(__dirname,'../dist/index.html'));createTab();win.on('resize',()=>apply())}
const onlyHttps=(u)=>{if(typeof u!=='string'||!http.test(u))throw new Error('Only http(s) URLs are allowed');return u};
app.whenReady().then(()=>{app.setAppUserModelId('com.xythol.mail');ipcMain.handle('app:get-version',()=>app.getVersion());ipcMain.handle('app:open-external',(_,u)=>shell.openExternal(onlyHttps(u)));ipcMain.handle('browser:attach',()=>apply());ipcMain.handle('browser:set-bounds',(_,b)=>{if(!b||b.width<=0||b.height<=0)throw new Error('Invalid browser bounds');bounds=b;apply()});ipcMain.handle('browser:navigate',async(_,u)=>{await current()?.view.webContents.loadURL(onlyHttps(u));return{ok:true}});ipcMain.handle('browser:back',()=>{if(current()?.view.webContents.canGoBack())current().view.webContents.goBack()});ipcMain.handle('browser:forward',()=>{if(current()?.view.webContents.canGoForward())current().view.webContents.goForward()});ipcMain.handle('browser:reload',()=>current()?.view.webContents.reload());ipcMain.handle('browser:home',()=>current()?.view.webContents.loadURL('https://www.google.com'));ipcMain.handle('browser:new-tab',()=>createTab());ipcMain.handle('browser:activate-tab',(_,id)=>{if(tabs.has(id)){activeId=id;apply();emit()}});ipcMain.handle('browser:close-tab',async(_,id)=>{const t=tabs.get(id);if(!t)return;win.contentView.removeChildView(t.view);t.view.webContents.close();tabs.delete(id);if(activeId===id){activeId=tabs.keys().next().value||null;if(!activeId)await createTab()}apply();emit()});ipcMain.handle('browser:save-current-source',()=>{const t=current();return t?{title:t.view.webContents.getTitle(),url:t.view.webContents.getURL(),domain:new URL(t.view.webContents.getURL()).hostname}:null});ipcMain.handle('browser:capture-selection',async()=>{const t=current();if(!t)return{ok:false,reason:'no-active-tab'};const text=await t.view.webContents.executeJavaScript('window.getSelection?String(window.getSelection()):""',true);return text?{ok:true,text,url:t.view.webContents.getURL(),title:t.view.webContents.getTitle()}:{ok:false,reason:'no-selection'}});ipcMain.handle('mail:send-smtp',async(_,p)=>{const {host,port,secure,username,password,from,to,cc,bcc,subject,text,html}=p;const tr=nodemailer.createTransport({host,port,secure,auth:{user:username,pass:password}});try{await tr.verify();await tr.sendMail({from,to,cc,bcc,subject,text,html});return{ok:true}}catch(e){return{ok:false,error:String(e)}}finally{tr.close()}});setup()});app.on('window-all-closed',()=>process.platform!=='darwin'&&app.quit());